### ISSUE TITLE
双击make.bat无法生存正确的地图

### ISSUE THREAD

**Issue by zhongying1995** [actboy168/MoeHero#1]
显示以下信息：

找不到 C:\Users\Administrator\Desktop\MoeHero-master\map\lua\currentpath.lua
C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\lua.exe: ...sers\Administrator\Desktop\MoeHero-master\tools\make.lua:8: module 'utility' not found:
        no field package.preload['utility']
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\lua\utility.lua'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\lua\utility\init.lua'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\utility.lua'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\utility\init.lua'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\..\share\lua\5.3\utility.lua'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\..\share\lua\5.3\utility\init.lua'
        no file '.\utility.lua'
        no file '.\utility\init.lua'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\..\w3x2lni\script\utility.lua'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\utility.dll'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\..\lib\lua\5.3\utility.dll'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\loadall.dll'
        no file '.\utility.dll'
        no file 'C:\Users\Administrator\Desktop\MoeHero-master\tools\bin\..\w3x2lni\bin\utility.dll'
stack traceback:
        [C]: in function 'require'
        ...sers\Administrator\Desktop\MoeHero-master\tools\make.lua:8: in main chunk
        [C]: in ?

**Comment by actboy168** [comment]
utility.lua是w3x2lni的一个文件，请确保你的w3x2lni的版本是正确的

**Comment by zhongying1995** [comment]
1.8.3最新的了吧，对文件的放置还有要求吗？

**Comment by actboy168** [comment]
不，w3x2lni是moehero的一个submodule，你应该用git来获取正确的版本，而不是自己放一个进去

**Comment by zhongying1995** [comment]
好吧，原来tool里面还需要一个w3x2lni................
