### ISSUE TITLE
关于dll签名dll.sign的问题

### ISSUE THREAD

**Issue by bamboo98** [actboy168/MoeHero#10]
因为要在lua层实现网络访问,需要加载socket库的core.dll,发现在19年1月2号的commit里有调用debugger.dll的地方
照葫芦画瓢发现好像需要给dll签名生成dll.sign才可以调用,tools文件夹里找到了rsa的签名工具,但是不知道使用的私钥和公钥需要在哪里生成以及公钥怎么导入到地图里

**Comment by sumneko** [comment]
这是内部使用的功能，出于安全考虑，不会开放签名。

**Comment by bamboo98** [comment]
唔姆...那签名的问题就不谈了...
那dll要怎样才能加载呢...现在打算做的地图必须得要socket连接才行啊...

**Comment by bamboo98** [comment]
翻了下代码发现加载dll时检查了签名...死循环了...
最后一点期望了...能不能把luasocket库开放进来...
我也不指望能加载任意dll...可以让我用socket就行
