### ISSUE TITLE
希望能补全一下文件

### ISSUE THREAD

**Issue by Sdator** [actboy168/MoeHero#12]
> Executing task: "chcp 65001 && "C:\War3\demo\201904/tools/w3x2lni/bin/w3x2lni-lua.exe"" .\tools\运行.lua C:\War3\demo\201904 <

Active code page: 65001
C:\War3\demo\201904/tools/w3x2lni/bin/w3x2lni-lua.exe: .\tools\运行.lua:1: module 'bee.filesystem' not found:
        no field package.preload['bee.filesystem']
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\lua\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\lua\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\share\lua\5.3\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\share\lua\5.3\bee\filesystem\init.lua'
        no file '.\bee\filesystem.lua'
        no file '.\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\lib\lua\5.3\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\loadall.dll'
        no file '.\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\lib\lua\5.3\bee.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\loadall.dll'
        no file '.\bee.dll'
stack traceback:
        [C]: in function 'require'
        .\tools\运行.lua:1: in main chunk
        [C]: in ?
终端进程已终止，退出代码: 1

终端将被任务重用，按任意键关闭。

> Executing task: "chcp 65001 && "C:\War3\demo\201904/tools/w3x2lni/bin/w3x2lni-lua.exe" -e "package.cpath=package.cpath..';'..[[C:\War3\demo\201904/tools/?.dll]]"" .\tools\语法检查.lua C:\War3\demo\201904 --watch <

Active code page: 65001
C:\War3\demo\201904/tools/w3x2lni/bin/w3x2lni-lua.exe: .\tools\语法检查.lua:1: module 'bee.filesystem' not found:
        no field package.preload['bee.filesystem']
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\lua\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\lua\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\share\lua\5.3\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\share\lua\5.3\bee\filesystem\init.lua'
        no file '.\bee\filesystem.lua'
        no file '.\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\lib\lua\5.3\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\loadall.dll'
        no file '.\bee\filesystem.dll'
        no file 'C:\War3\demo\201904/tools/bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\lib\lua\5.3\bee.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\loadall.dll'
        no file '.\bee.dll'
        no file 'C:\War3\demo\201904/tools/bee.dll'
stack traceback:
        [C]: in function 'require'
        .\tools\语法检查.lua:1: in main chunk
        [C]: in ?
终端进程已终止，退出代码: 1

终端将被任务重用，按任意键关闭。

> Executing task: "chcp 65001 && "C:\War3\demo\201904/tools/w3x2lni/bin/w3x2lni-lua.exe"" .\tools\运行.lua C:\War3\demo\201904 <

Active code page: 65001
C:\War3\demo\201904/tools/w3x2lni/bin/w3x2lni-lua.exe: .\tools\运行.lua:1: module 'bee.filesystem' not found:
        no field package.preload['bee.filesystem']
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\lua\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\lua\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\share\lua\5.3\bee\filesystem.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\share\lua\5.3\bee\filesystem\init.lua'
        no file '.\bee\filesystem.lua'
        no file '.\bee\filesystem\init.lua'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\lib\lua\5.3\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\loadall.dll'
        no file '.\bee\filesystem.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\bee.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\..\lib\lua\5.3\bee.dll'
        no file 'C:\War3\demo\201904\tools\w3x2lni\bin\loadall.dll'
        no file '.\bee.dll'
stack traceback:
        [C]: in function 'require'
        .\tools\运行.lua:1: in main chunk
        [C]: in ?
终端进程已终止，退出代码: 1

**Comment by sumneko** [comment]
你需要拉取子模块
git submodule update --init --recursive

**Comment by Sdator** [comment]
> 你需要拉取子模块
> git submodule update --init --recursive

临时研究了一下，虽然拉取成功了,但之前的错误依然还在。
下面是拉取成功的目录
```
DESKTOP MINGW64 /C/War3/demo/MoeHero/tools/w3x2lni ((377fe72e...))
$ ls
bin  build  c++  config.ini  data  docs  LICENSE.txt  log  README.md  script  template  test  w2l.exe  w3x2lni.exe
```

**Comment by sumneko** [comment]
拉下来的是源代码，你需要自己编译下。你也可以把最新发布版的w3x2lni的文件放进去。

**Comment by Sdator** [comment]
> 拉下来的是源代码，你需要自己编译下。你也可以把最新发布版的w3x2lni的文件放进去。

非常感谢，问题解决了，之前自己也拷贝过一次原来是我的w3x2lni版本太低导致的。

再请教一个问题，-reload指令这个如何使用，平时我都是手动保存重开这样测试起来太麻烦了，这个功能对我来说帮助很大。

**Comment by sumneko** [comment]
在obj模式下地图会从本地硬盘中加载脚本，reload做的事情就是把某些脚本重新从本地加载一次。Lua会把require过的文件返回值缓存在package.loaded表中，你只需要将这个表中相关的键值清除，require就可以再次加载文件。

**Comment by Sdator** [comment]
> 在obj模式下地图会从本地硬盘中加载脚本，reload做的事情就是把某些脚本重新从本地加载一次。Lua会把require过的文件返回值缓存在package.loaded表中，你只需要将这个表中相关的键值清除，require就可以再次加载文件。

这个重载指令需要自己来实现吗？还是已经提供了实现方法，比如直接在控制台中或游戏中输入-reload重载某个lua文件。  由于-reload指令的官方说明我没有找到更详细的信息以上只是个人猜测。

**Comment by sumneko** [comment]
需要自己实现

**Comment by Sdator** [comment]
> 需要自己实现

好的，也没什么问题了。目前使用lua作图，官方已经提供了很好的框架，实在不想自己再造轮子，现在一边看源码一边测试还是进度缓慢。希望作者可以考虑为萌英这个框架编写一些接口帮助文档。最后还是非常感谢你的解答，我也算是用上了最先进的作图方式了:D
