### ISSUE TITLE
当unit作为表的key被pairs遍历时会掉线的bug

### ISSUE THREAD

**Issue by w4454962** [actboy168/MoeHero#13]
在types\unit.lua中 init_unit 里 有一句 dbg.gchash(u, handle) 
handle可能出现异步 从而导致了 pairs 遍历哈希表时 的顺序不固定 而引起掉线

**Comment by w4454962** [comment]
![QQ图片20190426040407](https://user-images.githubusercontent.com/24670862/56773173-a08dc100-67ef-11e9-90b2-bd1502cab2f3.jpg)

如图 把gchash改为 不重复的num 或 处理所有引用unit的pairs即可

**Comment by actboy168** [comment]
说明你的ydwe版本太低

**Comment by w4454962** [comment]
不对 是你们的框架把 unit的gchash 指定为这个handle 即使你在底层写了 指定了个整数 也会被脚本中覆盖

**Comment by w4454962** [comment]
local u = {} 此时 c里给这个表指定了个 gchash
后又被 脚本中的 dbg.gchash(u,handle) 覆盖为 可能存在异步的handle id 
即 gchash 又恢复到不确定的状态下 
pairs 就 game over了 

所以跟版本无关 不管你有没有给 table 初始化一个 gchash 也会被这个handle覆盖

**Comment by actboy168** [comment]
新版本的ydwe,gchash只是一个空函数

**Comment by w4454962** [comment]
似乎不太行 经过玩家测试，即使把你所有1.32关于引擎部分的改动都移植了 ，在aura_buff 里面 有pairs 遍历 key为unit 的操作 还是有随机 会掉线， 所以还是在使用上尽量避免pairs就好了
