### ISSUE TITLE
句柄检测一直在增长，游戏越来越慢

### ISSUE THREAD

**Issue by ghost** [actboy168/MoeHero#19]
请问是何种原因

**Comment by sumneko** [comment]
一般说明有无用对象没有正确施放（内存泄漏）

**Comment by ghost** [comment]
怎么检测到是什么对象呢

**Comment by sumneko** [comment]
你可以在 level = 0 的情况下用整数遍历所有 handle ，然后用 `jass.debug` 库中的 `handledef` 函数查看 handle 的定义

**Comment by ghost** [comment]
level = 0 是指什么？大神指点

**Comment by sumneko** [comment]
见文档：https://github.com/actboy168/jass2lua/blob/master/lua-engine.md

**Comment by ghost** [comment]
游戏里面的ac代表什么

**Comment by sumneko** [comment]
我写的底层库喜欢放在ac命名的表里，历史原因而且打起来顺手

**Comment by ghost** [comment]
mt呢

**Comment by sumneko** [comment]
metatable的缩写

**Comment by ghost** [comment]
lua变量名混淆有什么库可以使用么  ，比如这种形式：

**Comment by ghost** [comment]
望大神指点

**Comment by ghost** [comment]
> 
> 
> 一般说明有无用对象没有正确施放（内存泄漏）

能不能把无用对象去掉

**Comment by ghost** [comment]
> 
> 
> > 一般说明有无用对象没有正确施放（内存泄漏）
> 
> 能不能把无用对象去掉

有工具检测吗

**Comment by ghost** [comment]
> 
> 
> 你可以在 level = 0 的情况下用整数遍历所有 handle ，然后用 `jass.debug` 库中的 `handledef` 函数查看 handle 的定义

如何遍历

**Comment by sumneko** [comment]
不回答这种基础语法问题或可以通过简单测试就可以解决的问题。

**Comment by oxpy** [comment]
我明白，关键是所有 handle存在哪里？遍历我会
