### ISSUE TITLE
BUG反馈：最新分支无法通过YDWE 1.31.8进行基于VSCode Lua Debug的Debug

### ISSUE THREAD

**Issue by Leginion** [actboy168/MoeHero#2]
* YDWE：1.31.8
* WAR3：1.24E
* 版本：https://github.com/actboy168/MoeHero/commit/5b557056c4f00407cd31ed7c7e8395444576a3b0
* Lua Debugger：https://github.com/actboy168/vscode-lua-debug/commit/f42847b42d3c23933ed5828931e898f34b2990dd

在此版本下fork后执行Task“运行”无法进入地图（会启动游戏但仅在开始界面）。
直接使用命令 `ydweconfig.exe -launchwar3 -loadfile "d:\moehero\moehero.w3x" -debugger 4278` 亦无法进入地图，修改为 `ydweconfig.exe -launchwar3 -loadfile "d:\moehero\moehero.w3x"` 后可启动地图，但无法使用VSCode进行Debug。

注：运行前已执行“生成”命令。

**Comment by actboy168** [comment]
你要用1.32.4

**Comment by Leginion** [comment]
谢谢
